services:
  server-1:
    image: andreevnikola/archtag-api:latest
    restart: always

  server-2:
    image: andreevnikola/archtag-api:latest
    restart: always

  server-3:
    image: andreevnikola/archtag-api:latest
    restart: always

  nginx:
    image: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "9999:9999"